# numpy.clip

### numpy.clip(a, a_min, a_max, out=None, **kwargs)[source]

numpy.clipはarrayの値のrangeを限定する関数。

### Parameters:	

|prams||
|---|----|
|a | array_like <br><br> Array containing elements to clip.|
|a_min | scalar or array_like or None <br><br> Minimum value. If None, clipping is not performed on lower interval edge. Not more than one of a_min and a_max may be None.|
|a_max | scalar or array_like or None <br><br> Maximum value. If None, clipping is not performed on upper interval edge. Not more than one of a_min and a_max may be None. If a_min or a_max are array_like, then the three arrays will be broadcasted to match their shapes.|
|out | ndarray, optional <br><br> The results will be placed in this array. It may be the input array for in-place clipping. out must be of the right shape to hold the output. Its type is preserved.|


### Examples

In [1]:
import numpy as np

In [2]:
a = np.arange(10)
np.clip(a, 1, 8)

array([1, 1, 2, 3, 4, 5, 6, 7, 8, 8])

In [3]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.clip(a, 3, 6, out=a)

array([3, 3, 3, 3, 4, 5, 6, 6, 6, 6])

In [5]:
a

array([3, 3, 3, 3, 4, 5, 6, 6, 6, 6])

In [6]:
a = np.arange(10)
np.clip(a, [3, 4, 1, 1, 1, 4, 4, 4, 4, 4], 8)

array([3, 4, 2, 3, 4, 5, 6, 7, 8, 8])