# Eigenvalues and Eigenvectors
## Agenda
- 固有値と固有ベクトル
- 正方行列の正則行列による対角化

### Hardware

In [1]:
%%bash
system_profiler SPHardwareDataType | grep -E \
"Model Identifier"\|"Processor Name"\|"Processor Speed"\
\|"Number of Processors"\|"Memory:"

      Model Identifier: MacBookPro13,1
      Processor Name: Dual-Core Intel Core i5
      Processor Speed: 2 GHz
      Number of Processors: 1
      Memory: 16 GB


In [2]:
!sw_vers

ProductName:	Mac OS X
ProductVersion:	10.15.4
BuildVersion:	19E287


### Python

In [3]:
!python -V

Python 3.7.4


### Install packages

In [4]:
pass

### Import

In [5]:
import numpy as np
from functools import reduce
import sympy 

### 関数

In [6]:
pass

## 1. 固有値と固有ベクトル

$$
A = [a_{ij}]
$$

はn次正方行列とする。

- 固有値とは、$A\mathbf x = \lambda \mathbf x, \mathbf x \neq 0$を満たすn次元列ベクトル$\mathbf x$が存在するような$\lambda$のこと
- 固有ベクトルとは、各固有値に対応する$A\mathbf x = \lambda \mathbf x, \mathbf x \neq 0$を満たすn次元列ベクトル$\mathbf x$
- 固有値は、一般には複数あるが、dimA 個以下



### 例題1

$$
A =\left[\begin{array}{ccc}
3 & -5 & -5\\
-1 & 7 & 5\\
1 & -9 & -7
\end{array}\right]
$$
の固有値と固有ベクトル(normは1に揃えよ)を求めよ。

[解答]

Aの固有方程式$\varphi(t)$は

$$
\varphi(t) = |A - tI_n| =\left|\begin{array}{ccc}
3-t & -5 & -5\\
-1 & 7-t & 5\\
1 & -9 & -7-t
\end{array}\right|
$$



In [7]:
t = sympy.Symbol('t')
expr = (3-t)*(7-t)*(-7-t)-70 + 5*(7-t) - 5*(-7-t) + 45 *(3- t)
print('eigenvalues are' , sympy.solve(expr))

eigenvalues are [-2, 2, 3]


対応する固有ベクトルの計算(-2を例とする)は

$$
\left[\begin{array}{ccc}
5 & -5 & -5\\
-1 & 9 & 5\\
1 & -9 & -5
\end{array}\right]\mathbf x = 0
$$


よって、
$$
\begin{aligned}
5x_1 - 5x_2 - 5x_3 &= 0\\
-x_1 + 9x_2 + 5x_3 &= 0
\end{aligned}
$$

Then,
$$
\mathbf x = \frac{1}{\sqrt 6}(1, -1,  2)^T
$$


### 固有方程式の根と係数の関係
$[\lambda_1, ..., \lambda_n]$を$A = [a_{ij}]$の固有値とすると

$$
\begin{aligned}
\Sigma \lambda_i &= tr(A)\\
\Pi \lambda_i & = |A|
\end{aligned}
$$

[証明]

$$
\varphi(t) = |A - t I_n| = (-1)^nt^n + (-1)^{n-1}t^{n-1}tr(A) + ... + |A|
$$

一方、Aの固有値は固有方程式の解なので

$$
\varphi(t) = (-1)^n(t - \lambda_1)...(t - \lambda_n)
$$

よって係数比較より自明。

### 正則条件

<img src = 'https://github.com/RyoNakagami/omorikaizuka/blob/master/algorithm/固有値正則条件.jpg?raw=true'>

### Pythonで確認

In [8]:
def eigenvalue_check(A):
    w, v = np.linalg.eig(A)
    res_1 = np.allclose(sum(w),np.trace(A))
    res_2 = np.allclose(reduce(lambda a, b: a*b, w), np.linalg.det(A))
    print(' trace check :', res_1, '\n','determinant check: ', res_2)

In [9]:
A = np.array([[9,10],[-6,-7]])
eigenvalue_check(A)

 trace check : True 
 determinant check:  True


In [10]:
A = np.array([[11,9],[-4,-1]])
eigenvalue_check(A)

 trace check : True 
 determinant check:  True


In [11]:
A = np.array([[5,-7, -7],[-4, 8, 7], [4, -10, -9]])
eigenvalue_check(A)

 trace check : True 
 determinant check:  True


In [12]:
A = np.random.randint(10, 100, 9).reshape(3,3)
eigenvalue_check(A)

 trace check : True 
 determinant check:  True


### 転置行列と固有多項式

$$
|A - \lambda I_n| = |(A - \lambda I_n)^T| = |A^T - \lambda I_n|
$$

より、転置行列の固有多項式は一致する。


## 2. Diagonalization(対角化)

n次正方行列Aに対して、正則行列Pを適当に選んで、$D = P^{-1}AP$とすると、$D$はAの対角化行列となる。

### 対角化条件

n次正方行列Aが対角化可能な必要十分条件は、Aがn個の線形独立な固有ベクトルを有することである。

In [13]:
A = np.array([[0.2,0.7, 0.1],[0.4,0.5, 0.1], [0.2, 0.6, 0.2]]).T
print(A)

[[0.2 0.4 0.2]
 [0.7 0.5 0.6]
 [0.1 0.1 0.2]]


In [14]:
w, v = np.linalg.eig(A)
print(w,'\n\n', v)

[ 1.  -0.2  0.1] 

 [[-4.74054679e-01 -7.07106781e-01 -5.34522484e-01]
 [-8.64452649e-01  7.07106781e-01 -2.67261242e-01]
 [-1.67313416e-01  2.67621717e-17  8.01783726e-01]]


In [15]:
D = np.linalg.inv(v)@A@v
D_1 = np.where(abs(D) > 1e-15, D, 0)
D_1

array([[ 1. ,  0. ,  0. ],
       [ 0. , -0.2,  0. ],
       [ 0. ,  0. ,  0.1]])

固有ベクトルの順番を変えてみると

In [16]:
D = np.linalg.inv(v[:,::-1])@A@v[:,::-1]
D_2 = np.where(abs(D) > 1e-15, D, 0)
D_2

array([[ 0.1,  0. ,  0. ],
       [ 0. , -0.2,  0. ],
       [ 0. ,  0. ,  1. ]])

なお行列のn乗は一致する

In [17]:
v@np.linalg.matrix_power(D_1, 10000)@np.linalg.inv(v)

array([[0.31481481, 0.31481481, 0.31481481],
       [0.57407407, 0.57407407, 0.57407407],
       [0.11111111, 0.11111111, 0.11111111]])

In [18]:
v[:,::-1]@np.linalg.matrix_power(D_2, 10000)@np.linalg.inv(v[:,::-1])

array([[0.31481481, 0.31481481, 0.31481481],
       [0.57407407, 0.57407407, 0.57407407],
       [0.11111111, 0.11111111, 0.11111111]])

### Matrix Powers

$$
A^k = (PDP^{-1})^k = PD^kP^{-1}
$$
との関係が知られている。


[証明]
$$
A^k = (PDP^{-1})^k = (PDP^{-1})(PDP^{-1})...(PDP^{-1})
$$

このとき、$PP^{-1} = I_n$より

$$
A^k = PD^kP^{-1}
$$



In [19]:
prob_raw = np.linalg.matrix_power(A, 10000)
prob_raw

array([[0.31481481, 0.31481481, 0.31481481],
       [0.57407407, 0.57407407, 0.57407407],
       [0.11111111, 0.11111111, 0.11111111]])

In [20]:
prob = v@np.linalg.matrix_power(D, 10000)@np.linalg.inv(v)
prob

array([[ 0.07407407,  0.07407407, -0.59259259],
       [ 0.03703704,  0.03703704, -0.2962963 ],
       [-0.11111111, -0.11111111,  0.88888889]])

### Page遷移確率への応用

$A = [a_{ij}]$をjからiへのページ遷移の確率を表す行列とする.この遷移行列の収束先はAの固有値のうち、1の値をとる固有値に対応する固有ベクトルの絶対値表現を正規化したものと一致する。

steady stateの条件より

$$
Av = v
$$

が成立するため(vはsteady stateベクトル)。


In [21]:
init = np.random.randint(1, 10, 3)
init = init/init.sum()
init

array([0.33333333, 0.25      , 0.41666667])

In [22]:
prob_raw @ init

array([0.31481481, 0.57407407, 0.11111111])

In [23]:
prob @ init

array([-0.2037037 , -0.10185185,  0.30555556])

In [24]:
abs(v[:,np.argmax(w)])/sum(abs(v[:,np.argmax(w)]))

array([0.31481481, 0.57407407, 0.11111111])

### 連立差分方程式

二つの数列$\{x_n\}, \{y_n\}$の間に

$$
\begin{cases}
x_n &= 7 x_{n-1} + 3 y_{n-1}\\
y_n & = x_{n-1} + 5 y_{n-1}
\end{cases}
$$

ただし、$(x_0, y_0) = (3, -2)$としたとき、

In [25]:
A = np.array([[7, 3],[1, 5]], dtype = float)
w, v = np.linalg.eig(A)
D = np.linalg.inv(v)@A@v
np.where(abs(D) > 1e-15, D, 0)

array([[8., 0.],
       [0., 4.]])

よって

$$
A^k = P\left(\begin{array}{cc}8 & 0\\ 0 & 4\end{array}\right)^kP^{-1}
$$

In [26]:
def calculate_transition(tran_mat, power, init):
    w, v = np.linalg.eig(tran_mat)
    D = np.linalg.inv(v)@tran_mat@v
    D = np.where(abs(D) > 1e-15, D, 0)
    return np.array(v@D**(power-1)@np.linalg.inv(v)@init, dtype = int)

In [27]:
calculate_transition(tran_mat = A, power = 2, init = np.array([3, -2]))

array([15, -6])

### 漸化式

$$
x_{n+2} - 4 x_{n+1} - 5 x_n = 0
$$

$(x_1, x_0) = (7, -1)$と与えられたとき、$x_{n+1} = y_n$と変形すると

$$
\begin{aligned}
x_{n} &=  y_{n-1}\\
y_{n} &= 4 y_{n-1} + 5 x_{n-1}
\end{aligned}
$$



In [28]:
A =  np.array([[0, 1],[5, 4]], dtype = float)
calculate_transition(tran_mat = A, power = 2, init = np.array([-1, 7]))

array([ 7, 23])