# 100 numpy exercises

||概要|
|---|---|
|目的|numpyに慣れるためのドリル|
|参考|https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises_with_solutions.md|


## 1. Import the numpy package under the name np

In [1]:
import numpy as np

## 2. Print the numpy version and the configuration

In [2]:
print(np.__version__)
np.show_config()

1.17.3
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


## 3. Create a null vector of size 10

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## 4. How to find the memory size of any array

In [4]:
# ndarray.itemsizeはLength of one array element in bytesを返す

Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


## 5. How to get the documentation of the numpy add function from the command line?

In [5]:
#%run `python -c "import numpy; numpy.info(numpy.add)"`

## 6. Create a null vector of size 10 but the fifth value which is 1 

In [6]:
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## 7. Create a vector with values ranging from 10 to 49

In [7]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## 8. Reverse a vector (first element becomes last)

In [8]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


## 9. Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
nz = np.arange(0, 9)
nz.shape = 3,3
nz

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [10]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


## 11. Create a 3x3 identity matrix 

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 12. Create a 3x3x3 array with random values 

In [12]:
## 引数はsize
np.random.random((3,3,3))

array([[[0.87621139, 0.46825876, 0.92563934],
        [0.74037709, 0.94816665, 0.64370504],
        [0.46441411, 0.20400154, 0.79262661]],

       [[0.11214282, 0.3289104 , 0.82251446],
        [0.96840533, 0.07406551, 0.68376653],
        [0.0651889 , 0.91987916, 0.39952859]],

       [[0.06688714, 0.71723237, 0.39459433],
        [0.61538115, 0.85680384, 0.88446686],
        [0.91886726, 0.87582116, 0.98639892]]])

## 13. Create a 10x10 array with random values and find the minimum and maximum values

In [13]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.0074760075208130106 0.9944619643827454


## 14. Create a random vector of size 30 and find the mean value

In [14]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.5246512346365468


## 15. Create a 2d array with 1 on the border and 0 inside 

In [15]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## 16. How to add a border (filled with 0's) around an existing array?

In [16]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=(1,1), mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


## 17. What is the result of the following expression?

In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


## 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [18]:
Z = np.diag(np.arange(1, 5),k = -1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


## 19. Create a 8x8 matrix and fill it with a checkerboard pattern 

In [19]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [20]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


## 21. Create a checkerboard 8x8 matrix using the tile function

In [21]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 22. Normalize a 5x5 random matrix

In [22]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 1.57493035  1.59908915  1.22393274 -0.05049877 -0.73050424]
 [ 1.04228773 -1.03158507  0.04899176 -1.35622059  0.97648635]
 [-1.0035222   0.18139111  1.73641738 -1.22548368  0.04678065]
 [ 0.10868226 -0.44785226  0.04798586 -1.3576135  -0.99729401]
 [-0.93203935 -0.75599025  1.52126372  0.43444232 -0.65407749]]


## 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [23]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

## 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [24]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


## 25. Given a 1D array, negate all elements which are between 3 and 8, in place

In [25]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


## 26. What is the output of the following script?

In [26]:
print(np.sum(range(5), initial = -1))

9


In [27]:
print(np.sum(range(5), axis = 0))

10


In [28]:
### If axis is negative it counts from the last to the first axis.
print(np.sum(range(5), axis = -1))

10


In [29]:
print(np.sum(range(5), axis = None))

10


### 27. interger vectorの挙動を確かめる

In [28]:
Z = np.random.randint(2, 8, size = 10)
Z

array([3, 6, 7, 5, 5, 4, 3, 2, 5, 7])

In [29]:
Z ** Z

array([    27,  46656, 823543,   3125,   3125,    256,     27,      4,
         3125, 823543])

In [30]:
Z * Z

array([ 9, 36, 49, 25, 25, 16,  9,  4, 25, 49])

In [31]:
Z @ Z

247

In [32]:
1j * Z

array([0.+3.j, 0.+6.j, 0.+7.j, 0.+5.j, 0.+5.j, 0.+4.j, 0.+3.j, 0.+2.j,
       0.+5.j, 0.+7.j])

In [33]:
type((Z/1/1)[0])

numpy.float64

### 28. What are the result of the following expressions?

In [49]:
print(np.array([np.nan]).astype(int).astype(float))

[-9.22337204e+18]


### 29. How to round away from zero a float array ?

In [52]:
Z = np.random.uniform(-10,+10,10)
Z

array([ 4.67381237, -7.43183582,  9.95049245, -3.8801222 ,  4.90161703,
       -2.56626733,  4.58010458, -1.7363236 , -4.33812108, -9.51841528])

In [56]:
print(np.copysign(np.ceil(np.abs(Z)), Z))

[  5.  -8.  10.  -4.   5.  -3.   5.  -2.  -5. -10.]


### 30. How to find common values between two arrays?

In [57]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 5 7 9]


### 31. How to ignore all numpy warnings (not recommended)? 

In [58]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


### 33. How to get the dates of yesterday, today and tomorrow?

In [63]:
print(np.datetime64('today', 'D') - np.timedelta64(1, 'D'))

2020-03-05


In [64]:
np.datetime64('today', 'D') - np.timedelta64(1, 'D')

numpy.datetime64('2020-03-05')

### 34. How to get all the dates corresponding to the month of July 2016?

In [65]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


### 35. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [71]:
A = np.ones(3)*1
B = np.ones(3)*2
(A + B) * (- A/2)

array([-1.5, -1.5, -1.5])

In [72]:
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

### 36. Extract the integer part of a random array using 5 different methods 

In [74]:
Z = np.random.uniform(0,10,10)
Z

array([2.46906756, 1.11214135, 3.79048213, 8.67752166, 1.67184208,
       1.59934431, 5.28031404, 3.6421789 , 3.34503774, 4.36674683])

In [78]:
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[2. 1. 3. 8. 1. 1. 5. 3. 3. 4.]
[2. 1. 3. 8. 1. 1. 5. 3. 3. 4.]
[2. 1. 3. 8. 1. 1. 5. 3. 3. 4.]
[2 1 3 8 1 1 5 3 3 4]
[2. 1. 3. 8. 1. 1. 5. 3. 3. 4.]


### 37. Create a 5x5 matrix with row values ranging from 0 to 4

In [81]:
Z = np.zeros((5,5))
Z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [82]:
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
