# 条件を満たす要素のindexを取得する`numpy.where`
## Agenda
- `numpy.where`を用いた配列操作を紹介

### Hardware

In [1]:
%%bash
system_profiler SPHardwareDataType | grep -E \
"Model Identifier"\|"Processor Name"\|"Processor Speed"\
\|"Number of Processors"\|"Memory:"

      Model Identifier: MacBookPro13,1
      Processor Name: Dual-Core Intel Core i5
      Processor Speed: 2 GHz
      Number of Processors: 1
      Memory: 16 GB


In [2]:
!sw_vers

ProductName:	Mac OS X
ProductVersion:	10.15.4
BuildVersion:	19E287


### Python

In [3]:
!python -V

Python 3.7.4


### Import

In [4]:
import numpy as np
from matplotlib import pyplot as plt
import pandas as pd

### Numpy version

In [5]:
np.__version__

'1.18.2'

## 1. `numpy.where`

- 条件をみたつ要素のindexを返す関数

### Syntax
```
numpy.where(condition[, x, y])
```

#### Parameters
- `condition`: array_like, bool

Where True, yield x, otherwise yield y.

- `x, y`: array_like

Values from which to choose. x, y and condition need to be broadcastable to some shape.

#### Returns

An array with elements from x where condition is True, and elements from y elsewhere.

### Note

arrayが1-Dの場合、`numpy.where`は以下のコードと挙動は一致する

```
[xv if c else yv
 for c, xv, yv in zip(condition, x, y)]
```

### Example: 1-D array

In [6]:
a = np.arange(10)
np.where(a < 5, a, a*100)

array([  0,   1,   2,   3,   4, 500, 600, 700, 800, 900])

### Example: 2-D array

In [7]:
np.where([[False, True], [True, True]],
          [[1, 2], [3, 4]],
          [[9, 8], [7, 6]])

array([[9, 2],
       [3, 4]])

In [8]:
np.where([[True, False], [True, True]],
          [[1, 2], [3, 4]],
          [[9, 8], [7, 6]])

array([[1, 8],
       [3, 4]])

In [9]:
np.where([[True, False], [False, True]],
          [[1, 2], [3, 4]],
          [[9, 8], [7, 6]])

array([[1, 8],
       [7, 4]])

### Indexの取得

In [10]:
a = np.arange(0, 12)
a += 10
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [11]:
np.where(a % 2 == 0)

(array([ 0,  2,  4,  6,  8, 10]),)