# 配列同士の連結
## Agenda

- `numpy.hstack`
- `numpy.vstack`
- `numpy.stack`

## 参考
- [Numpy tutorial](https://numpy.org/doc/1.18/user/quickstart.html?highlight=stack#stacking-together-different-arrays)

### Hardware

In [1]:
%%bash
system_profiler SPHardwareDataType | grep -E \
"Model Identifier"\|"Processor Name"\|"Processor Speed"\
\|"Number of Processors"\|"Memory:"

      Model Identifier: MacBookPro13,1
      Processor Name: Dual-Core Intel Core i5
      Processor Speed: 2 GHz
      Number of Processors: 1
      Memory: 16 GB


In [2]:
!sw_vers

ProductName:	Mac OS X
ProductVersion:	10.15.4
BuildVersion:	19E287


### Python

In [3]:
!python -V

Python 3.7.4


### Import

In [4]:
import numpy as np
from matplotlib import pyplot as plt

### Numpy version

In [5]:
np.__version__

'1.18.2'

## 1. `Numpy.hstack`の紹介

- `numpy.ndarray`をcolumn方向にstackする関数
- Stack arrays in sequence horizontally (column wise)とされている
- 厳密にいうと`axis = 1`の結合

### syntax

```
numpy.hstack(tup)[source]
```

In [6]:
a = np.array((1,2,3))
b = np.array((1,2,3))
np.hstack((a, b))

array([1, 2, 3, 1, 2, 3])

In [7]:
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])
c = np.hstack((a,b))
c.shape

(3, 2)

In [8]:
c

array([[1, 2],
       [2, 3],
       [3, 4]])

### 3D arrayの場合

- この場合は、 concatenate, stack and block といった関数を使用することが推奨される

In [9]:
a = np.arange(0, 27).reshape((3, 3, 3))
b = np.arange(28, 55).reshape((3, 3, 3))

In [10]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [11]:
b

array([[[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]],

       [[37, 38, 39],
        [40, 41, 42],
        [43, 44, 45]],

       [[46, 47, 48],
        [49, 50, 51],
        [52, 53, 54]]])

In [12]:
c = np.hstack((a, b))
c.shape

(3, 6, 3)

In [13]:
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [37, 38, 39],
        [40, 41, 42],
        [43, 44, 45]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [46, 47, 48],
        [49, 50, 51],
        [52, 53, 54]]])

## 2. `numpy.vstack`

- 垂直方向にarrayを結合(axis = 0)

### Syntax
```
numpy.vstack(tup)
```

In [14]:
a = np.array((1,2,3))
b = np.array((1,2,3))
np.vstack((a, b))

array([[1, 2, 3],
       [1, 2, 3]])

In [15]:
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])
c = np.vstack((a,b))
c.shape

(6, 1)

In [16]:
c

array([[1],
       [2],
       [3],
       [2],
       [3],
       [4]])

In [17]:
a = np.arange(0, 27).reshape((3, 3, 3))
b = np.arange(28, 55).reshape((3, 3, 3))
c = np.vstack((a,b))
c.shape

(6, 3, 3)

c

## 3. `Numpy.concatenate`

- `numpy.hstack`と`numpy.vstack`の一般化版
- concatenateは連結によって次元を上げることは出来ない
- 結合方向をaxisで指定できる

### Syntax

- `numpy.concatenate((a1, a2, ...), axis=0, out=None)`


In [18]:
a = np.array((1,2,3))
b = np.array((1,2,3))
np.concatenate((a, b))

array([1, 2, 3, 1, 2, 3])

In [19]:
a = np.array((1,2,3))
b = np.array((1,2,3))
np.concatenate((a, b), axis = 1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [20]:
a = np.array([[1,2,3]])
b = np.array([[1,2,3]])
np.concatenate((a, b), axis = 0)

array([[1, 2, 3],
       [1, 2, 3]])

In [21]:
a = np.array([[1,2,3]])
b = np.array([[1,2,3]])
np.concatenate((a, b), axis = 1)

array([[1, 2, 3, 1, 2, 3]])

## 4. `numpy.stack`

- 指定したaxis方向でarrayを結合する
- numpy.hstack, numpy.vstackとは別物と考えた方が良い
- axisは配列を重ねる方向を指定する
- 大きさがこなる配列を連結することはできない

### syntax

```
numpy.stack(arrays, axis=0, out=None
```

In [22]:
a = np.array((1,2,3))
b = np.array((1,2,3))
np.stack((a, b))

array([[1, 2, 3],
       [1, 2, 3]])

In [23]:
a = np.array((1,2,3))
b = np.array((1,2,3))
np.stack((a, b), axis = 1)

array([[1, 1],
       [2, 2],
       [3, 3]])

In [24]:
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])
np.stack((a,b))

array([[[1],
        [2],
        [3]],

       [[2],
        [3],
        [4]]])

In [25]:
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])
c = np.stack((a,b), axis = 1)
c.shape

(3, 2, 1)

In [26]:
c

array([[[1],
        [2]],

       [[2],
        [3]],

       [[3],
        [4]]])

## 5. 多次元配列の結合を行う`np.r_`, `np.c_`オブジェクト

- `np.c_`は`np.r_`の特殊ケースなので`np.r_`を習得すれば事足りる
- `np.c_`は`np.r_['-1,2,0', index expression]`と等しい

In [27]:
a = np.arange(0, 10)
b = np.arange(11, 21)
np.r_[a, b]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [28]:
np.c_[a, b]

array([[ 0, 11],
       [ 1, 12],
       [ 2, 13],
       [ 3, 14],
       [ 4, 15],
       [ 5, 16],
       [ 6, 17],
       [ 7, 18],
       [ 8, 19],
       [ 9, 20]])

### `Numpy.r_`とスライス表記

- `start:stop:step`で１次元配列を作成することができる

In [29]:
np.r_[0:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.r_[0:10:2]

array([0, 2, 4, 6, 8])

In [31]:
np.r_[10:0:-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [32]:
np.r_[0:9:10j]

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

### 文字列による軸と次元の指定

```
a,b,c
```

- `a`: どのaxisにそって配列を結合するかを指定
- `b`: 次元の最小数を指定
- `c`: 次元数の少ない配列の次元数の拡張を行った際、shapeの表記として、どこに配列の最後の次元が置かれるべきかを指定

In [33]:
a = np.arange(0, 9).reshape((3,3))
b = np.arange(9,18).reshape((3,3))

In [34]:
np.r_['0', a, b]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [35]:
np.r_['1', a, b]

array([[ 0,  1,  2,  9, 10, 11],
       [ 3,  4,  5, 12, 13, 14],
       [ 6,  7,  8, 15, 16, 17]])

In [36]:
np.all(np.hstack((a, b)) == np.r_['1', a, b])

True

In [37]:
np.all(np.vstack((a, b)) == np.r_['0', a, b])

True

### 最小次元数の指定

In [38]:
np.r_['0, 3', a, b]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [39]:
np.r_['1, 3', a, b]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

### 次元の拡張axis方向の指定

In [40]:
a = np.arange(0, 9)
b = np.arange(9,18)

In [41]:
np.r_['0, 2, 1', a, b]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17]])

In [42]:
np.r_['0, 2, 0', a, b]

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17]])

In [43]:
np.r_['1, 2, 1', a, b]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17]])

In [44]:
np.r_['1, 2, 0', a, b]

array([[ 0,  9],
       [ 1, 10],
       [ 2, 11],
       [ 3, 12],
       [ 4, 13],
       [ 5, 14],
       [ 6, 15],
       [ 7, 16],
       [ 8, 17]])

In [45]:
a = np.arange(0, 9).reshape((3,3))
b = np.arange(9,18).reshape((3,3))
np.r_['0, 3, 1', a, b]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [46]:
np.all(np.stack([a, b]) == np.r_['0, 3, 1', a, b])

True

In [47]:
np.r_['1, 3, 1', a, b]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

### 行列の指定

In [48]:
a = np.arange(0, 8)
b = np.arange(8, 16)
np.array(np.r_['c', a, b])

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [49]:
np.array(np.r_['r', a, b])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

### `np.c_`の例

In [50]:
np.c_[np.array([1,2,3]), np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [51]:
np.all(np.r_['1,2,0', np.array([1,2,3]), np.array([4,5,6])] == np.c_[np.array([1,2,3]), np.array([4,5,6])])

True

## 6. 配列に次元を追加する`np.newaxis` object

In [52]:
a = np.arange(0, 15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [53]:
a[np.newaxis, :, :]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]])

In [54]:
b = a.ravel()
b.reshape(15, -1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])

In [55]:
np.all(b[:, np.newaxis] == b.reshape(15, -1))

True

In [56]:
b.reshape(-1, 15)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [57]:
np.all(b[np.newaxis, :] == b.reshape(-1, 15))

True

#### Tips

- 配列への次元追加は`np.ndarray.reshape`を用いることでも可能だが、元の配列の各々の次元における要素数がわからなくても次元追加が可能な`np.newaxis`の方が実行が用意かつ可読性が高まるとされる